update README
senzowayne/resavo pull request #102
Opened 2021-04-29 06:50 UTC by ImenRad

Ajout installation avec composer

2021-04-29 06:53 UTC, ImenRad commented
J'ai intégré les modifications pour la base de données et pour mercure.

2021-05-03 14:31 UTC, senzowayne requested changes

2021-05-03 14:31 UTC, senzowayne commented on README.md
> +Sans docker, il nous faut installer le projet avec composer. Vous pouvez exécuter cette commande afin de pouvoir exploiter le projet en ligne de commande :
```suggestion
Il nous faut installer le projet avec composer. Vous pouvez exécuter cette commande afin de pouvoir exploiter le projet en ligne de commande :
```

On est déjà dans le sujet (Sans docker)

2021-05-03 14:31 UTC, senzowayne commented on README.md
> +$ composer
```suggestion
$ composer install
```

2021-05-03 14:31 UTC, senzowayne commented on README.md
> +Une fois composer et php bien installés, vous pouvez lancer le projet.
au moment ou tu nous invite à faire un` composer -v` ou` php -v` c'est déjà installé

2021-05-03 14:31 UTC, senzowayne commented on README.md
> +Créez une fichier .env.local avec comme variable d'environnement :
```suggestion
Pour mettre en place votre base de données,
Créez une fichier .env.local avec comme variable d'environnement : 
```

2021-05-03 14:31 UTC, senzowayne commented on README.md
> +DATABASE_PASSWORD=
```suggestion
DATABASE_NAME=resavo
DATABASE_HOST=localhost
DATABASE_PORT=3306
DATABASE_USER=!ChangeMe!
DATABASE_PASSWORD=!ChangeMe!
```

2021-05-03 14:31 UTC, senzowayne commented on README.md
> +Lien : http://127.0.0.1 ou http://localhost
Il vas peux être nous manquer la notion du lancement du serveur 
genre:
php bin/console server:start 
ou le virtualhost avec wamp 
à voir ce que vous avez mis en place lors de votre install

2021-05-03 19:50 UTC, senzowayne commented
Cf: https://symfony.com/blog/new-in-symfony-4-1-vardumper-server

2021-05-07 07:40 UTC, senzowayne requested changes

2021-05-07 07:40 UTC, senzowayne commented on README.md
> +Pour lancer le serveur de wamp, exécuter la commande suivante (pré-requis : Symfony CLI):
```suggestion
Pour lancer un serveur php, exécuter la commande suivante (pré-requis : Symfony CLI):
```

2021-05-07 09:55 UTC, senzowayne approved these changes

2021-05-07 09:56 UTC, merged